version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - mariadb
    ports:
      - 3000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  php:
    links:
      - mariadb
    build:
      context: ./docker/php/
    container_name: php
    volumes:
      - ./my-symfony-app:/usr/share/nginx/html
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env

  nginx:
    build:
      context: ./docker/nginx/
    restart: always
    container_name: nginx
    volumes:
      - ./my-symfony-app:/usr/share/nginx/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - 80:80
    depends_on:
      - php

volumes:
  mariadb:
    driver: local